# Generated by Django 2.2.1 on 2019-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='url',
            field=models.URLField(default='./templates/base.html'),
        ),
    ]
