# Generated by Django 2.2.1 on 2019-05-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_team_members_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_members',
            name='url',
            field=models.CharField(default='./templates/base.html', max_length=255),
        ),
    ]
