# Generated by Django 2.2.1 on 2019-06-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20190523_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../media/img/default.jpg', upload_to='image/founders')),
                ('name', models.CharField(default='Enter name', max_length=255)),
                ('url', models.CharField(default='./templates/base.html', max_length=255)),
            ],
        ),
    ]
